version: '3.8'

services:
    mysql_db:
        image: mysql:8.0.21
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: db_allocation
            MYSQL_USER: mysql_user
            MYSQL_PASSWORD: mysql_password
        ports:
            - 3306:3306

    phpmyadmin:
        image: phpmyadmin:5.0.4-apache
        restart: always
        ports:
          - 8081:80
        environment:
          - PMA_ARBITRARY=1

    server:
        build:
            context: ./
        restart: always
        ports:
            - 8080:8080
            - 5005:5005
        depends_on:
            - mysql_db
        command: sh ./run
        volumes:
            - ./:/professor-allocation
